// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGCGNuTS_rDXyKAYLyqu12fQa39i1CGG8',
    appId: '1:94130585461:web:734b2a51c6865ed5d2dd3c',
    messagingSenderId: '94130585461',
    projectId: 'kolab-f0831',
    authDomain: 'kolab-f0831.firebaseapp.com',
    storageBucket: 'kolab-f0831.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA_iaUQg6qH9yWWvGE_qkxbrskiY8lEx4',
    appId: '1:94130585461:android:51ef8c00a9a15f4ed2dd3c',
    messagingSenderId: '94130585461',
    projectId: 'kolab-f0831',
    storageBucket: 'kolab-f0831.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfHC_GcugmhglKV1TFhUdnnLC3i7--SWc',
    appId: '1:94130585461:ios:f3f54bd6fe096affd2dd3c',
    messagingSenderId: '94130585461',
    projectId: 'kolab-f0831',
    storageBucket: 'kolab-f0831.appspot.com',
    iosBundleId: 'com.example.kolab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfHC_GcugmhglKV1TFhUdnnLC3i7--SWc',
    appId: '1:94130585461:ios:28fe7113138af6ded2dd3c',
    messagingSenderId: '94130585461',
    projectId: 'kolab-f0831',
    storageBucket: 'kolab-f0831.appspot.com',
    iosBundleId: 'com.example.kolab.RunnerTests',
  );
}
